version: 2
jobs:
  build:
    docker:
      - image: node:18.10.0

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install
      - run: npm run lint

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      # - run: npm test

      # - run: npm build

      # - run: yarn netlify:deploy
  # lint:
  #   docker:
  #     - image: circleci/node:12.4
  #   working_directory: ~/repo
  #   steps:
  #     - checkout
  #     - run: npm install eslint
  #     - run: npm install eslint-plugin-react@latest --save-dev
  #     - run: npm run lint
# workflows:
#   version: 2
#   build:
#     jobs:
#       - build
#       - lint
